name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: pruebas-unitarias
        run: mvn test
      - name: Compile application without repeating tests
        run: mvn package -DskipTests=true

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: instalar aplicaci√≥n en Tomcat
        run: |
          mvn package -DskipTests=true
          cp -r target/Baloncesto /usr/local/tomcat/webapps
      - name: Prepare test database (Windows PowerShell)
        run: |
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      - name: realizar pruebas funcionales
        run: |
          mvn failsafe:integration-test failsafe:verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: calidad-codigo
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=adminn

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: descargar repostorio
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Desplegar en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: Baloncesto-Omar
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war
